server:
  port: 8080

spring:
  application:
    name: notification
---

spring:
  config:
    activate:
      on-profile: default
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        implicit_naming_strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
  cloud:
    function:
      routing-expression: "headers['type']=='IdentifiedAsFireEvent' ? 'wheneverIdentifiedAsFireEvent_NotifyFireEvent' : headers['type']=='StatusUpdated' ? 'wheneverStatusUpdated_NotifyFireEventUpdated' : headers['type']=='VideoAnalysisFailed' ? 'wheneverVideoAnalysisFailed_NotifyVideoAnalysisFailed' : headers['type']=='FireEventNotified' ? 'wheneverFireEventNotified_NotifyByLocation' : 'discardFunction'"
    stream:
      kafka:
        binder:
          brokers: localhost:9092
      bindings:
          functionRouter-in-0:              
            group: notification
            destination: fireresponsesystem
            contentType: application/json  
          producer-out-0:
            destination: fireresponsesystem
            contentType: application/json
logging:
  level:
    org.hibernate.type: trace
    org.springframework.cloud: debug


server:
  port: 8087

---

spring:
  config:
    activate:
      on-profile: docker
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        implicit_naming_strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
  cloud:
    function:
      routing-expression: "headers['type']=='IdentifiedAsFireEvent' ? 'wheneverIdentifiedAsFireEvent_NotifyFireEvent' : headers['type']=='StatusUpdated' ? 'wheneverStatusUpdated_NotifyFireEventUpdated' : headers['type']=='VideoAnalysisFailed' ? 'wheneverVideoAnalysisFailed_NotifyVideoAnalysisFailed' : headers['type']=='FireEventNotified' ? 'wheneverFireEventNotified_NotifyByLocation' : 'discardFunction'"
    stream:
      kafka:
        binder:
          brokers: my-kafka:9092
      bindings:
          functionRouter-in-0:              
            group: notification
            destination: fireresponsesystem
            contentType: application/json  
          producer-out-0:
            destination: fireresponsesystem
            contentType: application/json
            

