server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
#<<< API Gateway / Routes
      routes:
        - id: reportmanagement
          uri: http://localhost:8082
          predicates:
            - Path=/reports/**, 
        - id: videoproccessing
          uri: http://localhost:8083
          predicates:
            - Path=/videoAnalyses/**, /videos/**, 
        - id: eventmanagement
          uri: http://localhost:8084
          predicates:
            - Path=/events/**, 
        - id: aianalysis
          uri: http://localhost:8085
          predicates:
            - Path=/aiAnalyses/**, 
        - id: feedservice
          uri: http://localhost:8086
          predicates:
            - Path=/posts/**, 
        - id: notification
          uri: http://localhost:8087
          predicates:
            - Path=/notifications/**, /userAlarms/**, 
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**
#>>> API Gateway / Routes
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: reportmanagement
          uri: http://reportmanagement:8080
          predicates:
            - Path=/reports/**, 
        - id: videoproccessing
          uri: http://videoproccessing:8080
          predicates:
            - Path=/videoAnalyses/**, /videos/**, 
        - id: eventmanagement
          uri: http://eventmanagement:8080
          predicates:
            - Path=/events/**, 
        - id: aianalysis
          uri: http://aianalysis:8080
          predicates:
            - Path=/aiAnalyses/**, 
        - id: feedservice
          uri: http://feedservice:8080
          predicates:
            - Path=/posts/**, 
        - id: notification
          uri: http://notification:8080
          predicates:
            - Path=/notifications/**, /userAlarms/**, 
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
